### ISSUE TITLE
Question: Compatibility with InfluxDB v0.9

### ISSUE THREAD

**Issue by hkrizek** [influxdb/influxdb-java#22]
Hi,
do you have any plan to create java client compatible with InfluxDB v0.9 ?

**Comment by majst01** [comment]
I need to implement the v0.9 API but i have no concrete timeline for the moment.

**Comment by thetcc** [comment]
I need too！

**Comment by majst01** [comment]
Hi, 

i created a 0.9.0_support branch on github with my current work visible. This version is not meant to be published as is to maven repos, because i consider this as a first alpha version with some api breakage comming. 

To use it you have to clone the git repo and checkout the 0.9.0_support branch. 
then compile it with: 

mvn clean install -Dmaven.test.skip (not all tests pass actually) 

and then you can use the new library. 

It is not a plug in replacement to the existing 0.8 compatible library. 
Only writing, querying, creating/deleting/listing databases is currently supported. For Usage example look into InfluxDBTest.java. 

Feedback to this version is welcome, contributions as well. 

So please go test it :-) 

Greetings 
Stefan

**Comment by majst01** [comment]
Closing this ticket now, all problems with the new 0.9.0_support branch should be reported seperately
