### ISSUE TITLE
NPE thrown when working with InfluxDb 0.9 rc2

### ISSUE THREAD

**Issue by evgenyf** [influxdb/influxdb-java#24]
Method ping() worked properly with influxDb 0.8.
When we started to use InfluxDb version 0.9 rc2 method ping() failed with following exception:
2015-02-23 17:23:05,388  SEVERE [com.gigaspaces.webui.common] - java.lang.NullPointerException; Caused by: java.lang.NullPointerException
	at org.influxdb.impl.InfluxDBImpl.ping(InfluxDBImpl.java:107)

**Comment by majst01** [comment]
Hi Evgeny,

this is easily possible because the current version is in no way implemented against the v0.9 API of influxdb.  So if you need 0.9 support you need to wait. I will probably start 0.9 support after 0.9 is released.

**Comment by evgenyf** [comment]
Ok, thank you!

**Comment by evgenyf** [comment]
Hi
Are you still not supporting 0.9 InfluxDB? 
Thank you,
Evgeny

**Comment by majst01** [comment]
Im am currently working on a 0.9 branch but this will take at least 2 more weeks to be pushed to github.

**Comment by evgenyf** [comment]
ok, thank you for update!

**Comment by majst01** [comment]
Hi, 

i created a 0.9.0_support branch on github with my current work visible. This version is not meant to be published as is to maven repos, because i consider this as a first alpha version with some api breakage comming. 

To use it you have to clone the git repo and checkout the 0.9.0_support branch. 
then compile it with: 

mvn clean install -Dmaven.test.skip (not all tests pass actually) 

and then you can use the new library. 

It is not a plug in replacement to the existing 0.8 compatible library. 
Only writing, querying, creating/deleting/listing databases is currently supported. For Usage example look into InfluxDBTest.java. 

Feedback to this version is welcome, contributions as well. 

So please go test it  :-) 

Greetings 
Stefan

**Comment by majst01** [comment]
I will close this ticket, as this references a version which is not compatible with the 0.9 branch of influxdb,
