### ISSUE TITLE
java write data

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb-java#58]
i use the web client to write data,
{"table":"write_test","points":[{"table":"count","fields":{"value":5}}]}
return "bad request"
i want to do http api by myself. HttpURLConnection write the data is not useful

**Comment by majst01** [comment]
Hi @kcrosswind 

It is not clear how you wrote the given json data to influxdb. influxdb-java does not provide any api method to write against the json api because this feature was removed from influxdb-java some weeks ago as this feature is deprecated in influxdb.

And if you wrote your own client, i do not understand your question ?

Can you please elaborate more detailed.

Stefan

**Comment by kcrosswind** [comment]
hi @majst01 

thank you for you help. because my project is jdk 1.6, i can not use the influxdb-java, so i must do it for myself. now i use HttpURLConnection, and write the data 
{"database":"write_test","point":[{"table":"cpu","fields":{"value":5}}]}
nothing happen, i fail to wirte the data. and i can not find the struct of json to write

**Comment by kcrosswind** [comment]
my code is 
HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        con.setDoOutput(true);
        OutputStream wr = con.getOutputStream();
StringBuilder stringBuilder;
Stirng s = "{"database":"write_test","point":[{"table":"cpu","fields":{"value":5}}]}";
stringBuilder.append()
wr.write(stringBuilder.toString().getBytes(UTF_8));
wr.flush();
wr.close();

**Comment by majst01** [comment]
Hi @kcrosswind 

you can read how to write data here:
https://influxdb.com/docs/v0.9/guides/writing_data.html

There is no json endpoint available !

I dont understand why you start a new project with java 1.6 ? If you use java 1.7 or later, you can use the existing influxdb-java which covers all you need.

Greetings
Stefan

**Comment by kcrosswind** [comment]
hi @majst01

the web client: http://localhost:8083 is work, i use data explore to write data, but the json body is always wrong.
if json is not work.
how can the influxdb-java work? use http post?get? may be i can implement by my self, but i need to konw the params.
i want use java 1.7 ,but my old project can not.

**Comment by majst01** [comment]
You can always fork influxbd-java, set the java source level to 1.6, make it compile and use it like:

~~~java
InfluxDB influxDB = InfluxDBFactory.connect("http://172.17.0.2:8086", "root", "root");
String dbName = "aTimeSeries";
influxDB.createDatabase(dbName);

// Flush every 2000 Points, at least every 100ms
influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);

Point point1 = Point.measurement("cpu")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .field("idle", 90L).field("user", 9L)
                    .field("system", 1L)
                    .build();
Point point2 = Point.measurement("disk")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .field("used", 80L)
                    .field("free", 1L)
                    .build();

influxDB.write(dbName, "default", point1);
influxDB.write(dbName, "default", point2);
Query query = new Query("SELECT idle FROM cpu", dbName);
influxDB.query(query);
influxDB.deleteDatabase(dbName)
~~~

So as you can see there is no need to use HttpUrlConnection and friends anymore, you get a very Java agnostic API.

Hope this helps, im closing this ticket because i see no open problem on the influxdb-java side. Dont hesitate to open it again if you feel there are some bugs left.

Greetings
Stefan

**Comment by kcrosswind** [comment]
hi @majst01

thank you very much.
i think i should ask it in influxdb. it is not a influxdb-java problem.
sorry for the trouble.
