### ISSUE TITLE
Java 8?

### ISSUE THREAD

**Issue by Kindrat** [influxdb/influxdb-java#88]
What do you think about migrating to java 8?

**Comment by majst01** [comment]
the current version is already able to run under Java 8.

**Comment by Kindrat** [comment]
Actually I was talking about lambdas. To make 

```java
this.scheduler.scheduleAtFixedRate(new Runnable() {
    @Override
    public void run() {
        write();
    }
}, this.flushInterval, this.flushInterval, this.flushIntervalUnit);
```

look like

```java
this.scheduler.scheduleAtFixedRate(() -> this::write, this.flushInterval, this.flushInterval, this.flushIntervalUnit);
```

**Comment by majst01** [comment]
I know what is possible with java 8, but for the only reason to reduce the actual code by 5 lines of code i see no point to do it because we force all users of influxdb-java to switch to java 8 as well, which is from my standpoint not a valid option.

Keep always in mind that this is a library which a lot of people can use, and a library is all about add ass less friction as possible in adding it as dependency to the projects of others !

**Comment by bentatham** [comment]
Hmm...seems that java 8 has been introduced (for example, use of ``java.util.function.Consumer`` in PR #259, 5e743df, among other places).

However, the pom.xml still sets the java source/target to 1.7.  So I'm curious that status of java version here.
